language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-html-parser' ]; then cd .. && eval "mv $currentfolder generator-html-parser" && cd generator-html-parser; fi

